#!/usr/bin/env ksh
#####################################################################
# hsklogin - perform a "safe" login to the ssh-agent for an yubikey #
#            szymon@kapadia.pl                                      #
#####################################################################

life=57600 # 16 hours

usage() {
   echo 'usage: hsklogin [-t life] [-elLh]
     -t life: key life time in seconds
     -e: delete keys
     -l: display keys
     -L: dislpay keys in detail
     -h: print usage
     
     create keys using default life time:
      hsklogin

     create keys with an explicit life time (in seconds):
      hsklogin -t 6000

     delete installed keys:
      hsklogin -e'
}

while getopts ":helLt:" option; do
   case $option in
      h) # usage
         usage
         exit;;
      e) # remove keys
         ssh-add -e /usr/local/lib/libykcs11.dylib
         exit;;
      l) # list public key hashes
         ssh-add -l
         exit;;
      L) # list full public keys
         ssh-add -L
         exit;;
      t) # life: Set a maximum lifetime when adding identities to an agent.  The lifetime may be specified in seconds or in a time format specified in sshd_config(5).
         life=$OPTARG
         ;;
   esac
done

ssh-add -e /usr/local/lib/libykcs11.dylib > /dev/null 2>&1
if [[ $? == 0 ]]
  then
    echo -n "Existing keys removed..."
  else
    echo -n "No existing keys..."
fi


echo "Performing Login"
ssh-add -s /usr/local/lib/libykcs11.dylib -t $life > /dev/null 2>&1
if [[ $? == 0 ]] 
  then 
    echo "Keys added to agent"
    ssh-add -l
  else 
    echo "Failure: wrong pin or key not inserted"
fi
